name: openAbsorptionSolver-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pyqt
  - qtconsole
  - qtpy
  - scipy
  - seaborn
  - pip
  - pip:
      - buildingspy==4.0.0
      - cerberus==1.3.4
      - gitdb==4.0.9
      - gitpython==3.1.29
      - ofpp==0.11
      - pyfoam==2021.6
      - pyfunnel==0.3.0
      - pytidylib==0.3.2
      - pyyaml==6.0
      - simplejson==3.18.0

